#!/usr/bin/python

import requests

def ask_qa(title="Example question", text="This was generated by the SMS service", tags="new_support"):

    url = "193.15.15.34"
    URL1="http://%s:8080/account/signin/" % (url)
    #URL="http://localhost:8080/admin/login/?next=/admin/" % (url)
    URL2="http://%s:8080/account/signin/" % (url)
    URL3="http://%s:8080/questions/ask/" % (url)
    UN='bot'
    PWD='botbot'
    client = requests.session()
    
    # 1 just go to the page and Retrieve the CSRF token first
    client.get(URL1)  # sets the cookie
    csrftoken = client.cookies['csrftoken']
    client_cookies=client.cookies.get_dict()
    print(client_cookies)
    print(client.headers)
    
    # 2. log in with the credentials
    login_data = dict(
            csrfmiddlewaretoken=csrftoken,
            login_provider_name='local',
            next='',
            persona_assertion='',
            openid_login_token='',
            password_action='login',
            username=UN,
            password=PWD,
            login_with_password='Sign in',
            )
    r = client.post(URL2, data=login_data)#, headers={"Referer": "foo"})
    
    print(r)
    #f = open("output.html",'w')
    #f.write(r.content)
    #f.close()
    
    
    # 3. Ask a question
    cookies=r.cookies.get_dict()
    print(cookies)
    print(r.headers)
    headers = dict(
            askbot_visitor='False',
            csrftoken=cookies['csrftoken'],
            sessionid=client_cookies['sessionid']
            )
    
    
    form_data = dict(
        #csrfmiddlewaretoken=cookies['csrftoken'],
        csrfmiddlewaretoken=cookies['csrftoken'],
        #title="The cable is broken?",
        title=title,
        text=text,
        tags=tags,
        group_id='',
        post="Ask Your Question"
        )
    r = client.post(URL3, data=form_data, headers=headers)
    print(r)
    
    #f = open("output2.html",'w')
    #f.write(r.content)
    #f.close()

if __name__ == "__main__":
    ask_qa(title="Emma has a question", text="This was generated by the SMS service", tags="battery new_support")
